WebApp/Models/Personnes/Equipes/AddEquipeToTournoiViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models.Equipes;
using Unity;
using BO.Repository;
using BO.Model.Personnes.Equipes;
using BO.Model.Tournois;

namespace WebApp.Models.Personnes.Equipes
{
    public class AddEquipeToTournoiViewModel : EquipeViewModel
    {
        public List<string> tournoiId { get; set; }

        public List<SelectListItem> tournoiDispos { get; set; }


        public void InitData()
        {
            IRepository<TournoiJeuVideo> repoTournoi = UnityConfig.Container.Resolve<IRepository<TournoiJeuVideo>>();
            this.tournoiDispos = repoTournoi.GetAll(
                x => this.personnes.Count() ==  (int) x.Mode ).Select(
                s => new SelectListItem
                {
                    Text = s.Libelle,
                    Value = s.id.ToString(),
                }
                ).ToList();
        }
    } 
}

WebApp/Models/Personnes/Equipes/CreateEditEquipeViewModel.cs
using BO.Personnes;
using BO.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models.Equipes;
using Unity;
using BO.Model;
using System.ComponentModel;

namespace WebApp.Models.Personnes.Equipes
{
    public class CreateEditEquipeViewModel
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string CoachId { get; set; }

        [DisplayName("Joueurs")]
        public List<string> joueursSelect { get; set; }
        public List<SelectListItem> joueursDispo { get; set; }

        public void InitData()
        {
            IRepository<ApplicationUser> repoPersonne = UnityConfig.Container.Resolve<IRepository<ApplicationUser>>();
            this.joueursDispo = repoPersonne.GetAll(a => a.Roles.Select(s => s.RoleId).Contains("c5121754-19af-4e41-b1b9-997b1df59a2d")).Select(
                s => new SelectListItem
                {
                    Text = s.Nom,
                    Value = s.Id,
                    Disabled = s.Equipe != null && s.Equipe.id != this.Id,
                }
                ).ToList();
        }
    }
}

WebApp/Models/Personnes/Equipes/EquipeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using WebApp.Models.Personnes;
using WebApp.Models.Tournois;

namespace WebApp.Models.Equipes
{
    public class EquipeViewModel
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public int Point { get; set; }
        public string CoachId { get; set; }

        [DisplayName("Joueurs")]
        public List<PersonneViewModel> personnes { get; set; }
    }
}

WebApp/Controllers/EquipesController.cs
using BO.Model;
using BO.Model.Personnes.Equipes;
using BO.Personnes;
using BO.Repository;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Extensions;
using WebApp.Mapper;
using WebApp.Models.Equipes;
using WebApp.Models.Personnes.Equipes;

namespace WebApp.Controllers
{
    public class EquipesController : Controller
    {
        private IRepository<Equipe> _repository;
        private IRepository<ApplicationUser> _repositoryP;

        public EquipesController()
        {

        }

        public EquipesController(IRepository<Equipe> repository, IRepository<ApplicationUser> repositoryP)
        {
            this._repository = repository;
            this._repositoryP = repositoryP;
        }
        // GET: Equipes
        public ActionResult Index()
        {
            var equipes = _repository.GetAll();
            return View(equipes.Select(s => s.Map<EquipeViewModel>()));
        }

        // GET: Equipes/Details/5
        public ActionResult Details(int id)
        {
            return View(this._repository.Get(id).Map<EquipeViewModel>());
        }

        // GET: Equipes/Create
        [Authorize(Roles = "Admin, Entraineur")]
        public ActionResult Create()
        {
            var CEEqupe = new CreateEditEquipeViewModel();
            CEEqupe.CoachId = User.Identity.GetUserId();
            CEEqupe.InitData();
            return View("CreateEdit", CEEqupe);
        }

        // GET: Equipes/Edit/5
        [Authorize(Roles = "Admin, Entraineur")]
        public ActionResult Edit(int id)
        {
            var CEEqupe = this._repository.Get(id).Map<CreateEditEquipeViewModel>();
            CEEqupe.InitData();
            return View("CreateEdit", CEEqupe);
        }

        // POST: Equipes/Edit/5
        [HttpPost]
        [Authorize(Roles = "Admin, Entraineur")]
        public ActionResult CreateEdit(int id, CreateEditEquipeViewModel equipeViewModel)
        {
            if (ModelState.IsValid)
            {
                var personnes = this._repositoryP.GetAll(s => equipeViewModel.joueursSelect.Contains(s.Id.ToString()));
                var equipe = this._repository.Get(equipeViewModel.Id);
                if (equipe == null)
                {
                    equipe = new Equipe();
                    this._repository.Create(equipe);
                }
                equipe = AutoMapper.Mapper.Map(equipeViewModel, equipe);
                equipe.personnes = personnes;

                this._repository.Commit();
                return RedirectToAction("Index");
            }
            return View(equipeViewModel);
        }

        // GET: Equipes/Delete/5
        [Authorize(Roles = "Admin, Entraineur")]
        public ActionResult Delete(int id)
        {
            return View(this._repository.Get(id).Map<EquipeViewModel>());
        }

        // POST: Equipes/Delete/5
        [HttpPost]
        [Authorize(Roles = "Admin, Entraineur")]
        public ActionResult Delete(int id, EquipeViewModel equipeViewModel)
        {
            try
            {
                this._repository.Delete(id);
                this._repository.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View(equipeViewModel);
            }
        }
    }
}

WebApp/Controllers/PersonnesController.cs
using BO;
using BO.Model;
using BO.Model.Personnes.Equipes;
using BO.Personnes;
using BO.Repository;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Extensions;
using WebApp.Models;
using WebApp.Models.Personnes;

namespace WebApp.Controllers
{
    public class PersonnesController : Controller
    {
        private IRepository<Equipe> _repoEquipe;
        private IRepository<ApplicationUser> _repoUser;

        public PersonnesController()
        {
        }

        public PersonnesController(IRepository<Equipe> repoEquipe, IRepository<ApplicationUser> repoUser)
        {
            this._repoEquipe = repoEquipe;
            this._repoUser = repoUser;
            }


        // GET: Personnes
        public ActionResult Index()
        {
            List<PersonneViewModel> personnesVM = this._repoUser.GetAll().Select(a => a.Map<PersonneViewModel>()).ToList();
            return View(personnesVM);
        }

        // GET: Personnes/Details/5
        public ActionResult Details(string id)
        {
            PersonneViewModel personneVM = this._repoUser.GetAll().Where(a => a.Id == id).Select(a => a.Map<PersonneViewModel>()).FirstOrDefault();
            return View(personneVM);
        }

        // GET: Personnes/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(string id)
        {
            EditViewPersonne personneVM = this._repoUser.GetAll().Where(a => a.Id == id).Select(a => a.Map<EditViewPersonne>()).FirstOrDefault();
            ApplicationDbContext context = new ApplicationDbContext();

            var storeUser = new UserStore<ApplicationUser>(context);
            var managerUser = new UserManager<ApplicationUser>(storeUser);

            personneVM.RoleId = managerUser.GetRoles(personneVM.Id).FirstOrDefault();
            return View(personneVM);
        }

        // POST: Personnes/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Edit(string id, EditViewPersonne editViewPersonne, ApplicationDbContext context)
        {
            try
            {
                var storeUser = new UserStore<ApplicationUser>(context);
                var managerUser = new UserManager<ApplicationUser>(storeUser);
                ApplicationUser user = this._repoUser.GetAll(a => a.Id == id).First();
                  
                if (user == null)
                {
                    View(editViewPersonne);
                }

                user.Nom = editViewPersonne.Nom;
                user.Prenom = editViewPersonne.Prenom;
                user.UserName = editViewPersonne.Pseudonyme;
                user.DateNaissance = editViewPersonne.DateNaissance;
                user.Email = editViewPersonne.Mail;

                string userRole = managerUser.GetRoles(user.Id).FirstOrDefault();
                managerUser.RemoveFromRole(user.Id, userRole);
                managerUser.AddToRole(user.Id, editViewPersonne.RoleId);

                this._repoUser.Commit();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(editViewPersonne);
            }
        }

        // GET: Personnes/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string id)
        {
            PersonneViewModel personneVM = this._repoUser.GetAll().Where(a => a.Id == id).Select(a => a.Map<EditViewPersonne>()).FirstOrDefault();
            return View(personneVM);
        }

        // POST: Personnes/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Delete(string id, PersonneViewModel personneViewModel)
        {
            try
            {
                this._repoUser.Delete(id);
                this._repoUser.Commit();

                return RedirectToAction("Index");
            }
            catch
            {
                return View(personneViewModel);
            }
        }
    }
}

WebApp/Views/Equipes/CreateEdit.cshtml
@model WebApp.Models.Personnes.Equipes.CreateEditEquipeViewModel

@{
    if (Model.Id == 0)
    {
        ViewBag.Title = "Ajouter";
    }
    else
    {
        ViewBag.Title = "Modifier";
    }

}

@if (Model.Id == 0)
{
    <h2>Ajouter</h2>
}
else
{
    <h2>Modifier</h2>
}


@using (Html.BeginForm("CreateEdit","Equipes"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Equipe</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CoachId)
        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.joueursSelect, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.joueursSelect, Model.joueursDispo)
                @Html.ValidationMessageFor(model => model.joueursSelect, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sauvegarder" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retourner à la liste d'équipe", "Index", null, new { @class = "btn btn-default" })
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script>
jQuery(document).ready(function(){
    $('select').multipleSelect({
        filter: true,
        width: 280,
    });
});
</script>
}

WebApp/Views/Equipes/Delete.cshtml
@model WebApp.Models.Equipes.EquipeViewModel

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Voulez-vous supprimer cette équipe ?</h3>
<div>
    <h4>Equipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Point)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Point)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retourner à la liste d'équipe", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

WebApp/Views/Equipes/Details.cshtml
@model WebApp.Models.Equipes.EquipeViewModel

@{
    ViewBag.Title = "Détails";
}

<h2>Détails</h2>

<div>
    <h4>Equipe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Point)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Point)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.personnes)
        </dt>

        <dd>
            @string.Join(", ", Model.personnes.Select(s => s.Pseudonyme))
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modifier", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning" }) |
    @Html.ActionLink("Retourner à la liste d'équipe", "Index", null, new { @class = "btn btn-default" })
</p>

WebApp/Views/Equipes/Index.cshtml
@model IEnumerable<WebApp.Models.Equipes.EquipeViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
   @if (User.IsInRole("Admin, Entraineur"))
   { @Html.ActionLink("Ajouter une nouvelle équipe", "Create", null, new { @class = "btn btn-default" })}
    @Html.ActionLink("Liste des Joueurs", "Index", "Personnes", null, new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Point)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.personnes)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Point)
        </td>
        <td>
           @string.Join(", ", item.personnes.Select(s => s.Pseudonyme));
        </td>
        <td>
           @if (User.IsInRole("Admin"))
           { @Html.ActionLink("Modifier", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" }) }
            @Html.ActionLink("Détails", "Details", new { id = item.Id }, new { @class = "btn btn-primary" }) 
           @if (User.IsInRole("Admin"))
           { @Html.ActionLink("Supprimer", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })}
        </td>
    </tr>
}

</table>