WebApp/Models/Jeux/JeuVideoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using WebApp.Models.Jeux;

namespace WebApp.Models
{
    public class JeuVideoViewModel
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public virtual List<SupportViewModel> Supports { get; set; }

        [DisplayName("Age Limite")]
        public int AgeLimite { get; set; }
    }
}

WebApp/Controllers/JeuVideoController.cs
using BO;
using BO.Model.Jeux;
using BO.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using WebApp.Models;
using WebApp.Extensions;

namespace WebApp.Controllers
{
    public class JeuVideoController : Controller
    {
        private IRepository<JeuVideo> _repositoryJeuVideo;
        private IRepository<Support> _repositorySupport;

        public JeuVideoController(IRepository<JeuVideo> repositoryJeuVideo, IRepository<Support> repositorySupport)
        {
            this._repositoryJeuVideo = repositoryJeuVideo;
            this._repositorySupport = repositorySupport;
        }
        public ActionResult Index()
        {
            var jeuxvideo = this._repositoryJeuVideo.GetAll();
            return View(jeuxvideo.Select(j => j.Map<JeuVideoViewModel>()));
        }

        // GET: JeuVideo/Details/5
        public ActionResult Details(int id)
        {
            return View(this._repositoryJeuVideo.Get(id).Map<JeuVideoViewModel>());
        }

        // GET: JeuVideo/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View("CreateEdit", new CreateEditJeuVideo());
        }

        // GET: JeuVideo/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var jeuVideoCE = this._repositoryJeuVideo.Get(id).Map<CreateEditJeuVideo>();
            return View("CreateEdit", jeuVideoCE);
        }

        // POST: JeuVideo/CreateEdit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult CreateEdit(CreateEditJeuVideo createEditJeuVideo)
        {
            if (ModelState.IsValid)
            {
                List<Support> supports = this._repositorySupport.GetAll(s => createEditJeuVideo.SupportSelected.Contains(s.id.ToString()));
                JeuVideo jeuVideo = this._repositoryJeuVideo.Get(createEditJeuVideo.Id);
                if(jeuVideo == null)
                {
                    jeuVideo = new JeuVideo();
                    this._repositoryJeuVideo.Create(jeuVideo);
                }
                jeuVideo = AutoMapper.Mapper.Map(createEditJeuVideo, jeuVideo);
                jeuVideo.Supports = supports;

                this._repositoryJeuVideo.Commit();
                return RedirectToAction("Index");
            }

            return View(createEditJeuVideo);
        }

        // GET: JeuVideo/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            var jeuVideoVM = this._repositoryJeuVideo.Get(id).Map<JeuVideoViewModel>();
            return View(jeuVideoVM);
        }

        // POST: JeuVideo/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                this._repositoryJeuVideo.Delete(id);
                this._repositoryJeuVideo.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApp/Controllers/SupportsController.cs
using BO.Model.Jeux;
using BO.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Extensions;
using WebApp.Models.Jeux;

namespace WebApp.Controllers
{
    public class SupportsController : Controller
    {
        private IRepository<Support> _repositorySupport;

        public SupportsController(IRepository<Support> repositorySupport)
        {
            this._repositorySupport = repositorySupport;
        }
        // GET: Supports
        public ActionResult Index()
        {
            var support = this._repositorySupport.GetAll();
            return View(support.Select(j => j.Map<SupportViewModel>()));
        }

        // GET: Supports/Details/5
        public ActionResult Details(int id)
        {
            return View(this._repositorySupport.Get(id).Map<SupportViewModel>());
        }

        // GET: Supports/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View("CreateEdit", new SupportViewModel());
        }

        // GET: Supports/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id)
        {
            var supprotCE = this._repositorySupport.Get(id).Map<SupportViewModel>();
            return View("CreateEdit", supprotCE);
        }

        // POST: JeuVideo/CreateEdit/5
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult CreateEdit(SupportViewModel SupportVM)
        {
            if (ModelState.IsValid)
            {
                Support support = this._repositorySupport.Get(SupportVM.Id);
                if (support == null)
                {
                    support = new Support();
                    this._repositorySupport.Create(support);
                }
                support = AutoMapper.Mapper.Map(SupportVM, support);

                this._repositorySupport.Commit();
                return RedirectToAction("Index");
            }

            return View(SupportVM);
        }

        // GET: Supports/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            var supprotVM = this._repositorySupport.Get(id).Map<SupportViewModel>();
            return View(supprotVM);
        }

        // POST: Supports/Delete/5
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                this._repositorySupport.Delete(id);
                this._repositorySupport.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApp/Views/JeuVideo/CreateEdit.cshtml
@model WebApp.Models.CreateEditJeuVideo

@{
    if(Model.Id == 0)
    {
        ViewBag.Title = "Ajouter";
    }
    else
    {
        ViewBag.Title = "Modifier";
    }

}

@if (Model.Id == 0)
{
    <h2>Ajouter</h2>
}
else
{
    <h2>Modifier</h2>
}



@using (Html.BeginForm("CreateEdit", "JeuVideo"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Jeux Vidéo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
            <br><br>
            @Html.LabelFor(model => model.AgeLimite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AgeLimite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AgeLimite, "", new { @class = "text-danger" })
            </div>
            <br><br>
            @Html.LabelFor(model => model.Supports, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(model => model.SupportSelected, Model.Supports, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupportSelected, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enregistrer" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retourner à la liste de Jeux Vidéo", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp/Views/JeuVideo/Delete.cshtml
@model WebApp.Models.JeuVideoViewModel

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Voulez-vous supprimer cette élément?</h3>
<div>
    <h4>Jeux Vidéo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgeLimite)
        </dt>
        <dd>
            @Html.DisplayFor(modelItem => Model.AgeLimite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supports)
        </dt>
        <dd>
            @string.Join(", ", Model.Supports.Select(i => i.libelle))
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-danger" /> |
            @Html.ActionLink("Retourner à la liste de Jeux Vidéo", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

WebApp/Views/JeuVideo/Details.cshtml
@model WebApp.Models.JeuVideoViewModel

@{
    ViewBag.Title = "Détails";
}

<h2>Détails</h2>

<div>
    <h4>Jeux Vidéo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AgeLimite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AgeLimite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Supports)
        </dt>

        <dd>
            @string.Join(", ", Model.Supports.Select(s => s.libelle))
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Modifier", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning" }) |
    @Html.ActionLink("Retourner à la liste de Jeux Vidéo", "Index", null, new { @class = "btn btn-default" })
</p>

WebApp/Views/JeuVideo/Index.cshtml
@model IEnumerable<WebApp.Models.JeuVideoViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @if (User.IsInRole("Admin"))
    {@Html.ActionLink("Ajouter un nouveau jeux vidéo", "Create", null, new { @class = "btn btn-default" })} 
    @Html.ActionLink("Liste des Support", "Index", "Supports", null, new { @class = "btn btn-default" })
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nom)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AgeLimite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Supports)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AgeLimite)
        </td>
        <td>
            @string.Join(", ", item.Supports.Select(i => i.libelle))
        </td>
        <td>
            @if (User.IsInRole("Admin"))
            {@Html.ActionLink("Modifier", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" })}
            @Html.ActionLink("Détails", "Details", new { id = item.Id }, new { @class = "btn btn-primary" }) 
           @if (User.IsInRole("Admin"))
           { @Html.ActionLink("Supprimer", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })}
        </td>
    </tr>
    }

</table>