WebApp/Models/Tournois/CreateEditTournoiViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Models.Tournois
{
    public class CreateEditTournoiViewModel
    {
        List<int> EquipesId { get; set; }
        List<SelectListItem> EquipesForList { get; set; }
        List<int> TypesTournoiId { get; set; }
        List<SelectListItem> TypesTournoiForList { get; set; }
        List<int> MatchsId { get; set; }
        List<SelectListItem> MatchsForList { get; set; }

    }
}

WebApp/Models/Tournois/CreateEditTournoisJeuVideoViewModel.cs
using BO.Model.Jeux;
using BO.Model.Personnes.Equipes;
using BO.Model.Tournois;
using BO.Repository;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Unity;

namespace WebApp.Models.Tournois
{
    public class CreateEditTournoisJeuVideoViewModel
    {
        public int Id { get; set; }

        [DisplayName("Nom")]
        public string Libelle { get; set; }
        public DateTime Date { get; set; }

        [DisplayName("Cash Prize")]
        public float CashPrize { get; set; }
        public string Reglement { get; set; }
        public List<SelectListItem> Equipes { get; set; }
        public List<string> equipesId { get; set; }
        public float Prix { get; set; }
        public List<SelectListItem> Matchs { get; set; }
        public List<string> MatchsId { get; set; }
        public List<SelectListItem> Modes { get; set; }

        [DisplayName("Mode")]
        public string ModeId { get; set; }

        [DisplayName("Nombre d'équipe maximum")]
        public int NombreEquipeMax { get; set; }

        [DisplayName("Jeux Vidéo")]
        public List<SelectListItem> JeuVideos { get; set; }
        public string JeuVideoId { get; set; }

        public void InitList()
        {
            this.Modes = Enum.GetValues(typeof(Mode)).Cast<Mode>().Select(s => new SelectListItem { Value = ((int)s).ToString(), Text = s.ToString() }).ToList();

            IRepository<JeuVideo> repoJeuVideo = UnityConfig.Container.Resolve<IRepository<JeuVideo>>();
            this.JeuVideos = repoJeuVideo.GetAll().Select(s => new SelectListItem { Value = s.id.ToString(), Text = s.Nom }).ToList();
        }
    }
}

WebApp/Models/Tournois/MatchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApp.Models.Equipes;

namespace WebApp.Models.Tournois
{
    public class MatchViewModel
    {
        public int Id { get; set; }
        public string NomEquipeGagnante { get; set; }
        public List<EquipeViewModel> Equipes { get; set; }
    }
}

WebApp/Models/Tournois/TournoiJeuVideoViewModel.cs
using BO.Model.Tournois;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace WebApp.Models.Tournois
{
    public class TournoiJeuVideoViewModel : TournoiViewModel
    {
        public Mode Mode { get; set; }

        [DisplayName("Nombre d'équipe maximum")]
        public int NombreEquipeMax { get; set; }

        [DisplayName("Jeu Vidéo")]
        public virtual JeuVideoViewModel JeuVideo { get; set; }
    }
}

WebApp/Models/Tournois/TournoiViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using WebApp.Models.Equipes;

namespace WebApp.Models.Tournois
{
    public class TournoiViewModel
    {
        public int Id { get; set;  }

        [DisplayName("Equipe gagnante")]
        public string EquipeGagnante { get; set; }

        [DisplayName("Nom")]
        public string Libelle { get; set; }
        public DateTime Date { get; set; }

        [DisplayName("Cash Prize")]
        public float CashPrize { get; set; }
        public string Reglement { get; set; }
        public List<EquipeViewModel> equipes { get; set; }
        public float Prix { get; set; }
        public List<MatchViewModel> Matchs { get; set; }
    }
}

WebApp/Controllers/TournoisController.cs
using BO.Model.Jeux;
using BO.Model.Personnes.Equipes;
using BO.Model.Tournois;
using BO.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Extensions;
using WebApp.Models.Tournois;

namespace WebApp.Controllers
{
    public class TournoisController : Controller
    {
        private IRepository<TournoiJeuVideo> _repositoryTournoiJeuVideo;
        private IRepository<Match> _repositoryMatch;
        private IRepository<Equipe> _repositoryEquipe;
        private IRepository<JeuVideo> _repositoryJeuVideo;

        public TournoisController(IRepository<TournoiJeuVideo> _repositoryTournoiJeuVideo, 
                                    IRepository<Match> _repositoryMatch,
                                    IRepository<Equipe> _repositoryEquipe, 
                                    IRepository<JeuVideo> _repositoryJeuVideo)
        {
            this._repositoryTournoiJeuVideo = _repositoryTournoiJeuVideo;
            this._repositoryMatch = _repositoryMatch;
            this._repositoryEquipe = _repositoryEquipe;
            this._repositoryJeuVideo = _repositoryJeuVideo;
        }
        // GET: Tournois
        public ActionResult Index()
        {
            var tournoisjeuxvideo = this._repositoryTournoiJeuVideo.GetAll();
            return View(tournoisjeuxvideo.Select(j => j.Map<TournoiJeuVideoViewModel>()));
        }

        // GET: Tournois/Details/5
        public ActionResult Details(int id)
        {
            var tournoi = this._repositoryTournoiJeuVideo.Get(id);
             if(tournoi.Matchs.Count() != 0 && tournoi.Matchs.Where(c => c.NomEquipeGagnante == null || c.NomEquipeGagnante.Equals("")).Count() < 1)
            {
                tournoi.EquipeGagnante = tournoi.Equipes.Where(c => c.Point == tournoi.Equipes.Select(s => s.Point).Max()).Select(m => m.Nom).FirstOrDefault();
                foreach(var i in tournoi.Equipes)
                {
                    i.Point = 0;
                }
                this._repositoryEquipe.Commit();
                this._repositoryTournoiJeuVideo.Commit();
            }
       
            return View(tournoi.Map<TournoiJeuVideoViewModel>());
        }

        // GET: Tournois/Create
        [Authorize(Roles = "Admin, Organisateur")]
        public ActionResult Create()
        {
            var CETournoisVM = new CreateEditTournoisJeuVideoViewModel();
            CETournoisVM.InitList();
            return View("CreateEdit", CETournoisVM);
        }

        // GET: Tournois/Edit/5
        [Authorize(Roles = "Admin, Organisateur")]
        public ActionResult Edit(int id)
        {
            var tournoisjeuVideoCE = this._repositoryTournoiJeuVideo.Get(id).Map<CreateEditTournoisJeuVideoViewModel>();
            tournoisjeuVideoCE.InitList();
            return View("CreateEdit", tournoisjeuVideoCE);
        }

        // POST: JeuVideo/CreateEdit/5
        [Authorize(Roles = "Admin, Organisateur")]
        [HttpPost]
        public ActionResult CreateEdit(CreateEditTournoisJeuVideoViewModel ceTournoisJeuVideo)
        {
            if (ModelState.IsValid)
            {
                var JeuVideo = this._repositoryJeuVideo.Get(int.Parse(ceTournoisJeuVideo.JeuVideoId));
                var mode = Enum.GetValues(typeof(Mode)).Cast<Mode>().Where(s => ((int)s).ToString() == ceTournoisJeuVideo.ModeId).FirstOrDefault();
                TournoiJeuVideo tournoisjeuvideo = this._repositoryTournoiJeuVideo.Get(ceTournoisJeuVideo.Id);
                if (tournoisjeuvideo == null)
                {
                    tournoisjeuvideo = new TournoiJeuVideo();
                    this._repositoryTournoiJeuVideo.Create(tournoisjeuvideo);
                }
                tournoisjeuvideo = AutoMapper.Mapper.Map(ceTournoisJeuVideo, tournoisjeuvideo);
                tournoisjeuvideo.JeuVideo = JeuVideo;
                tournoisjeuvideo.Mode = mode;

                this._repositoryTournoiJeuVideo.Commit();
                return RedirectToAction("Index");
            }

            return View(ceTournoisJeuVideo);
        }

        // GET: Tournois/Delete/5
        [Authorize(Roles = "Admin, Organisateur")]
        public ActionResult Delete(int id)
        {
            var tournoisjeuVideoVM = this._repositoryTournoiJeuVideo.Get(id).Map<TournoiJeuVideoViewModel>();
            return View(tournoisjeuVideoVM);
        }

        // POST: Tournois/Delete/5
        [Authorize(Roles = "Admin, Organisateur")]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                this._repositoryTournoiJeuVideo.Delete(id);
                this._repositoryTournoiJeuVideo.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApp/Views/Tournois/CreateEdit.cshtml
@model WebApp.Models.Tournois.CreateEditTournoisJeuVideoViewModel

@{
    if (Model.Id == 0)
    {
        ViewBag.Title = "Ajouter";
    }
    else
    {
        ViewBag.Title = "Modifier";
    }

}

@if (Model.Id == 0)
{
    <h2>Ajouter</h2>
}
else
{
    <h2>Modifier</h2>
}

@using (Html.BeginForm("CreateEdit", "Tournois"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tournois de Jeux Vidéo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Libelle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Libelle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Libelle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CashPrize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CashPrize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CashPrize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ModeId, Model.Modes, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.ModeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreEquipeMax, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreEquipeMax, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreEquipeMax, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JeuVideos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.JeuVideoId, Model.JeuVideos, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.JeuVideoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Reglement, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Reglement, new { @class = "form-control", rows = "5", style= "resize: none;" } )
                @Html.ValidationMessageFor(model => model.Reglement, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sauve" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retourner à la liste de Tournois de Jeux Vidéo", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApp/Views/Tournois/Delete.cshtml
@model WebApp.Models.Tournois.TournoiJeuVideoViewModel

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Voulez-vous supprimer cette élément?</h3>
<div>
    <h4>Tournoi de Jeux Video</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CashPrize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CashPrize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reglement)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Reglement)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreEquipeMax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreEquipeMax)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-danger" /> |
            @Html.ActionLink("Retourner à la liste de Tournois de Jeux Vidéo", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

WebApp/Views/Tournois/Details.cshtml
@model WebApp.Models.Tournois.TournoiJeuVideoViewModel

@{
    ViewBag.Title = "Détails";
}

<h2>Détails</h2>

<div>
    <h4>Tournoi Jeu Video</h4>
    
    <p>
        @if (User.IsInRole("Admin"))
        {
            @Html.ActionLink("Modifier", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning" }) 
            
        }
        @Html.ActionLink("Retourner à la liste de Tournois de Jeux Vidéo", "Index", null, new { @class = "btn btn-default" })
    </p>
    <hr /> 
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CashPrize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CashPrize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prix)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prix)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreEquipeMax)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreEquipeMax)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EquipeGagnante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EquipeGagnante)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reglement)
        </dt>

        <dd>
            @Html.Raw(Model.Reglement.Replace("\r\n", "<br>"))
        </dd>
        <br>
        <h3>Liste des équipes inscrites</h3>
        <br>
        @Html.ActionLink("Voir la liste des Matchs", "../Matchs/Index", new { id = Model.Id }, new { @class = "btn btn-default" })
        <br>
        <br>
        <table class="table">
            <tr>
                <th>
                    Nom
                </th>
                <th>
                    Points
                </th>
                <th>
                    Personnes
                </th>
                <th>
                </th>
            </tr>

            @foreach (var item in Model.equipes)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nom)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Point)
                    </td>
                    <td>
                        @string.Join(", ", item.personnes.Select(s => s.Pseudonyme));
                    </td>
                    <td>
                        @Html.ActionLink("Détail équipe", "../Equipes/Details", new { id = item.Id }, new { @class = "btn btn-default" })
                    </td>
                </tr>
            }

        </table>
    </dl>
</div>

WebApp/Views/Tournois/Index.cshtml
@model IEnumerable<WebApp.Models.Tournois.TournoiJeuVideoViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Ajouter un nouveau tournoi de jeux vidéo", "Create", null, new { @class = "btn btn-default" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Libelle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CashPrize)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Prix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NombreEquipeMax)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EquipeGagnante)
        </th>
        @if (User.IsInRole("Admin"))
        {
        <th></th>}
        <th></th>
        @if (User.IsInRole("Admin"))
            {
        <th></th>}
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Libelle)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CashPrize)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prix)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreEquipeMax)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EquipeGagnante)
            </td>
            @if (User.IsInRole("Admin"))
            {
                <td>
                    @Html.ActionLink("Modifier", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" })
                </td>
            }
            <td>
                @Html.ActionLink("Détails", "Details", new { id = item.Id }, new { @class = "btn btn-primary" })
            </td>
            @if (User.IsInRole("Admin"))
            {
                <td>
                    @Html.ActionLink("Supprimer", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>
            }
        </tr>
    }


</table>